// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: query.sql

package db

import (
	"context"
)

const getAllLogs = `-- name: GetAllLogs :many
SELECT id, mensagem FROM Logs
`

func (q *Queries) GetAllLogs(ctx context.Context) ([]Log, error) {
	rows, err := q.db.QueryContext(ctx, getAllLogs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Log
	for rows.Next() {
		var i Log
		if err := rows.Scan(&i.ID, &i.Mensagem); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
